// Success stories — static data
// To add a new story, append an entry to the STORIES array below.
const STORIES = [
    {
        id: 1,
        name: "T.K",
        occupation: "Engineer",
        exam: "CLF-C02",
        examLabel: "CLF - Cloud Practitioner",
        score: 780,
        studyMonths: 2,
        dailyMinutes: 30,
        shortComment: "I passed just by studying during my commute! The explanations were clear and easy to follow.",
        motivation: "I started using AWS at work and wanted to validate my foundational knowledge.",
        howToUse: "I made it a habit to answer 5–10 questions on the train every morning (20-minute commute). Reading the explanations carefully gave me a solid overview of each AWS service.",
        schedule: "Weekdays: 10–15 questions during commute (both ways) / Weekends: one full mock exam",
        struggles: "IAM policy structure was confusing at first, but it clicked naturally after repeating the questions a few times.",
        examTip: "The exam gives you plenty of time. Flag questions you're unsure about and come back to them at the end.",
        nextGoal: "SAA-C03"
    },
    {
        id: 2,
        name: "M.S",
        occupation: "Sales (non-technical)",
        exam: "CLF-C02",
        examLabel: "CLF - Cloud Practitioner",
        score: 820,
        studyMonths: 3,
        dailyMinutes: 45,
        shortComment: "Passed with zero IT background. The detailed term explanations made all the difference.",
        motivation: "I wanted to build cloud knowledge to improve my sales proposals.",
        howToUse: "I split my sessions into lunch break and just before bed. Using the 'review later' feature to revisit wrong answers was especially effective.",
        schedule: "Lunch break: 15 min + before bed: 30 min",
        struggles: "Cloud concepts were completely new to me — my accuracy was around 30% in the first week. I kept pushing through the explanations and it gradually improved.",
        examTip: "Focus on understanding why a particular service is the right choice, not just memorising names.",
        nextGoal: "AIF-C01"
    },
    {
        id: 3,
        name: "R.T",
        occupation: "Infrastructure Engineer",
        exam: "SAA-C03",
        examLabel: "SAA - Solutions Architect Associate",
        score: 850,
        studyMonths: 4,
        dailyMinutes: 60,
        shortComment: "The large question bank covers the full exam scope. The mock exams were especially useful.",
        motivation: "I wanted to join our company's cloud migration project as an architect.",
        howToUse: "I used category-based study to focus on weak areas like VPC, EC2, and S3. In the final two weeks I took one mock exam every day to get comfortable with the timing.",
        schedule: "Weekdays: 1 hour after work / Weekends: 2–3 hours",
        struggles: "SAA has many design-scenario questions that can't be cracked by rote memorisation. I had to practice reading each question with an eye on cost vs. availability trade-offs.",
        examTip: "When you see keywords like 'most cost-effective' or 'minimum operational overhead', use them to guide your answer.",
        nextGoal: "SAP-C02"
    },
    {
        id: 4,
        name: "A.Y",
        occupation: "Backend Engineer",
        exam: "DVA-C02",
        examLabel: "DVA - Developer Associate",
        score: 795,
        studyMonths: 2,
        dailyMinutes: 40,
        shortComment: "Questions around Lambda and DynamoDB overlapped with my day job — it was actually fun to study.",
        motivation: "I wanted to systematise my serverless development knowledge.",
        howToUse: "I narrowed my focus to developer-oriented services (Lambda, API Gateway, DynamoDB, CI/CD with the Code suite). Real-world overlap kept my motivation high.",
        schedule: "Morning routine: 30 min before work / Lunch break: 10 min",
        struggles: "Telling SQS, SNS, and Kinesis apart tripped me up right to the end. Drawing out the differences on paper finally made it stick.",
        examTip: "X-Ray and CloudWatch questions are reliable point-scorers — make sure you nail them.",
        nextGoal: "SAA-C03"
    },
    {
        id: 5,
        name: "K.N",
        occupation: "Data Engineer",
        exam: "AIF-C01",
        examLabel: "AIF - AI Practitioner",
        score: 810,
        studyMonths: 1,
        dailyMinutes: 60,
        shortComment: "Perfect for consolidating AI/ML concepts. The generous coverage of generative AI topics matched the real exam well.",
        motivation: "I was working on a generative AI project and wanted a clear picture of the full AWS AI services landscape.",
        howToUse: "One month of intensive study. I organised questions by service (SageMaker, Bedrock, Rekognition, etc.) and made a rule to redo every wrong answer three times.",
        schedule: "Weekdays: 1 hour after work / Weekends: 2 hours in the morning",
        struggles: "Responsible AI principle questions felt abstract and hard to choose between. Reading the official AWS documentation on the principles cleared things up.",
        examTip: "Bedrock model-selection questions often ask 'which model best fits this use case?' — a table summarising each model's strengths will pay off.",
        nextGoal: "MLA-C01"
    },
    {
        id: 6,
        name: "H.O",
        occupation: "SRE",
        exam: "SAP-C02",
        examLabel: "SAP - Solutions Architect Professional",
        score: 760,
        studyMonths: 6,
        dailyMinutes: 90,
        shortComment: "The Professional level was tough, but consistent bite-sized study sessions got me through.",
        motivation: "I wanted to be able to design large-scale multi-account environments.",
        howToUse: "Six months of preparation after passing SAA. I focused heavily on services that SAA barely touches — Organizations, Control Tower, and Transit Gateway.",
        schedule: "Weekdays: 30 min morning + 1 hour evening / Weekends: 3 hours in the morning",
        struggles: "The questions are long and the scenarios are complex — almost like a reading comprehension test. Focusing on elimination (crossing out answers that are clearly wrong) pushed my accuracy up.",
        examTip: "Professional questions often include a plausible-but-wrong option as a trap. Never overlook constraints like cost, time, or existing systems.",
        nextGoal: "DOP-C02"
    }
];
