// 合格体験記 静的データ
// 新しい体験記を追加するにはこの配列に要素を追加してください
const STORIES = [
    {
        id: 1,
        name: "T.K",
        occupation: "エンジニア",
        exam: "CLF-C02",
        examLabel: "CLF - Cloud Practitioner",
        score: 780,
        studyMonths: 2,
        dailyMinutes: 30,
        shortComment: "通勤中だけで合格できました！解説が丁寧で理解しやすかったです。",
        motivation: "業務でAWSを使い始めたので、まず基礎を証明したくて受験しました。",
        howToUse: "毎朝の通勤電車（片道20分）でスキマラーニングの問題を5〜10問解くのを習慣にしました。解説をしっかり読むことで、サービスの概要をざっと把握できました。",
        schedule: "平日：通勤往復で10〜15問 / 休日：模擬試験を1回",
        struggles: "IAMのポリシー構造が最初は混乱しましたが、繰り返し問題を解くうちに自然と整理されました。",
        examTip: "試験当日は時間に余裕があるので、わからない問題はフラグを立てて後回しにするのが有効です。",
        nextGoal: "SAA-C03"
    },
    {
        id: 2,
        name: "M.S",
        occupation: "非エンジニア（営業職）",
        exam: "CLF-C02",
        examLabel: "CLF - Cloud Practitioner",
        score: 820,
        studyMonths: 3,
        dailyMinutes: 45,
        shortComment: "IT未経験でも合格できました。用語解説が丁寧で助かりました。",
        motivation: "営業として提案力を上げるためにクラウドの知識を身につけたかった。",
        howToUse: "昼休みと就寝前の2回に分けて問題を解きました。間違えた問題を「後で見直す」機能でまとめて復習したのが特に効果的でした。",
        schedule: "昼休み15分 + 就寝前30分",
        struggles: "クラウドの概念自体が初めてで、最初の1週間は正答率が30%台でした。諦めずに解説を読み込み続けたら徐々に上がりました。",
        examTip: "暗記より「なぜそのサービスを選ぶのか」の理由を理解することが大切です。",
        nextGoal: "AIF-C01"
    },
    {
        id: 3,
        name: "R.T",
        occupation: "インフラエンジニア",
        exam: "SAA-C03",
        examLabel: "SAA - Solutions Architect Associate",
        score: 850,
        studyMonths: 4,
        dailyMinutes: 60,
        shortComment: "問題数が多く試験範囲を網羅できた。模擬試験が特に役立ちました。",
        motivation: "社内のクラウド移行プロジェクトにアーキテクトとして関わりたかった。",
        howToUse: "カテゴリ別学習でVPC・EC2・S3など苦手分野を集中的に攻略。最後の2週間は毎日模擬試験を1回ずつ受けて時間感覚を養いました。",
        schedule: "平日1時間（帰宅後） / 週末2〜3時間",
        struggles: "SAAは設計シナリオ問題が多く、単純な暗記では対応できませんでした。コスト最適化 vs 可用性のトレードオフを意識して問題を読む練習が必要でした。",
        examTip: "問題文に「最もコスト効率が良い」「最小限の運用負荷」などキーワードがあれば、それに沿った選択肢を選ぶのがコツです。",
        nextGoal: "SAP-C02"
    },
    {
        id: 4,
        name: "A.Y",
        occupation: "バックエンドエンジニア",
        exam: "DVA-C02",
        examLabel: "DVA - Developer Associate",
        score: 795,
        studyMonths: 2,
        dailyMinutes: 40,
        shortComment: "Lambda・DynamoDB周りが実務と重なって楽しく勉強できました。",
        motivation: "サーバーレス開発の知識を体系化したかった。",
        howToUse: "開発系サービス（Lambda, API Gateway, DynamoDB, CodeシリーズなどCI/CD）に絞ってカテゴリ学習。実務知識が活きる問題が多く、モチベーションを保ちやすかった。",
        schedule: "朝活：出社前30分 / 昼休み10分",
        struggles: "SQS・SNS・Kinesisの使い分けが最後まで混乱しました。図を書いて違いを整理し直してようやく定着しました。",
        examTip: "Xray・CloudWatchの問題は確実に取りに行くと点数が安定します。",
        nextGoal: "SAA-C03"
    },
    {
        id: 5,
        name: "K.N",
        occupation: "データエンジニア",
        exam: "AIF-C01",
        examLabel: "AIF - AI Practitioner",
        score: 810,
        studyMonths: 1,
        dailyMinutes: 60,
        shortComment: "AI/MLの概念整理に最適。生成AI関連の問題が豊富で本番に直結しました。",
        motivation: "生成AIプロジェクトに関わる中で、AWS AIサービスの全体像を把握したかった。",
        howToUse: "1ヶ月の短期集中。SageMaker・Bedrock・Rekognitionなどサービス別に問題を分類して学習。間違えた問題は3回解き直すルールを設けました。",
        schedule: "平日：帰宅後1時間 / 休日：午前中2時間",
        struggles: "責任あるAI（Responsible AI）の原則問題は抽象的で正答を選びにくかった。AWS公式ドキュメントの原則を読んだら理解が深まりました。",
        examTip: "Bedrockのモデル選択問題は「ユースケースに合った最適なモデルはどれか」という形式が多い。各モデルの特徴を表でまとめると良いです。",
        nextGoal: "MLA-C01"
    },
    {
        id: 6,
        name: "H.O",
        occupation: "SRE",
        exam: "SAP-C02",
        examLabel: "SAP - Solutions Architect Professional",
        score: 760,
        studyMonths: 6,
        dailyMinutes: 90,
        shortComment: "Professional レベルは難しかったですが、スキマ学習の積み重ねで突破できました。",
        motivation: "大規模マルチアカウント環境の設計ができるようになりたかった。",
        howToUse: "SAA合格から半年かけて準備。Organizations・Control Tower・Transitゲートウェイなど、SAAでは深掘りしないサービスを重点的に学習しました。",
        schedule: "平日：朝30分＋夜1時間 / 休日：午前中3時間",
        struggles: "問題が長文でシナリオが複雑。読解力が問われる感覚でした。選択肢を「確実に間違い」から消す消去法を意識すると正答率が上がりました。",
        examTip: "Professionalは答えが「惜しいもの」を引っ掛けとして入れてくることが多い。制約条件（コスト・時間・既存システム）を見逃さないで。",
        nextGoal: "DOP-C02"
    }
];
